[workspace.package]
version = "0.3.4"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["David Cattermole"]

[workspace]
members = [
    "configure-bin",
    "core",
    "dump-bin",
    "print-bin",
    "print-lib",
    "recorder-bin",
]

resolver = "2"
