# Alma Linux 9 is binary-compatible with Red Hat Enterprise Linux (RHEL) 9.
#
# To create and run the docker container in PowerShell or Bash:
#
# $ sudo systemctl start docker  # If docker engine isn't already started.
# $ sudo docker build --file share/docker/Dockerfile_almalinux9 -t timetracker-linux-almalinux9-build .
# $ sudo docker run --rm --interactive --volume "${PWD}:/timetracker" --tty timetracker-linux-almalinux9-build
#
# Then build the project:
#
# $ cargo test
# $ cargo build --all --release
#
# To package the resulting binaries for release to users:
# $ cd target/release/
# $ zip ../../timetracker-almalinux9-v0.4.x.zip timetracker-print timetracker-print-gui timetracker-recorder timetracker-dump timetracker-configure
#

FROM almalinux:9.3

# GCC (C++ compiler), Gnome Toolkit (GTK) and X11 dependencies.
# 'zip' is installed for packaging.
RUN dnf install --assumeyes \
       gcc \
       glib2 \
       glib2-devel \
       pango-devel \
       gtk3-devel \
       atk-devel \
       cairo-devel \
       libX11 \
       libX11-devel \
       libXScrnSaver \
       libXScrnSaver-devel \
       zip

# Install latest stable Rust with 'rustup'.
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && source ${HOME}/.cargo/env

WORKDIR /timetracker
ENTRYPOINT ["bash"]
