name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y librust-gtk-dev libgdk3.0-cil libgdk3.0-cil-dev libgtk3.0-cil libgtk3.0-cil-dev libatk1.0-dev libpango1.0-dev libcairo2-dev libgio3.0-cil-dev libglib3.0-cil-dev libx11-6 libx11-dev libxss1 libxss-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
